name: Lighthouse CI

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 9 * * *' # daily at 09:00 UTC
  push:
    branches: [ main ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Lighthouse CI (production URLs)
        run: |
          npx @lhci/cli@0.14.x autorun --config=.lighthouserc.json
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
